from datetime import datetime, timezone
from enum import Enum


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class UserRole(str, Enum):
    CANDIDATE = "CANDIDATE"
    EMPLOYER = "EMPLOYER"
    RECRUITER = "RECRUITER"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"
    FINANCE = "FINANCE"
    EDITOR = "EDITOR"


class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    SUSPENDED = "SUSPENDED"
    DEACTIVATED = "DEACTIVATED"


class JobSearchStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PASSIVE = "PASSIVE"
    NOT_LOOKING = "NOT_LOOKING"
    HIRED = "HIRED"


class CompanyMemberRole(str, Enum):
    OWNER = "OWNER"
    MEMBER = "MEMBER"
    BILLING = "BILLING"


class JobStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    PUBLISHED = "PUBLISHED"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class ApplicationStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    RECEIVED = "RECEIVED"
    UNDER_REVIEW = "UNDER_REVIEW"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW = "INTERVIEW"
    SECOND_INTERVIEW = "SECOND_INTERVIEW"
    OFFER_SENT = "OFFER_SENT"
    REJECTED = "REJECTED"
    HIRED = "HIRED"
    WITHDRAWN = "WITHDRAWN"


class CompanyStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PROSPECT = "PROSPECT"
    INACTIVE = "INACTIVE"


class MissionStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"


class ContractStatus(str, Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    DRAFT = "DRAFT"


class NotificationType(str, Enum):
    APPLICATION_NEW = "APPLICATION_NEW"
    APPLICATION_STATUS = "APPLICATION_STATUS"
    JOB_MATCH = "JOB_MATCH"
    INTERVIEW_INVITE = "INTERVIEW_INVITE"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    RESUME_UPDATED = "RESUME_UPDATED"
    APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    ADMIN = "ADMIN"
    MESSAGE = "MESSAGE"
    DOCUMENT_ADDED = "DOCUMENT_ADDED"
    SYSTEM = "SYSTEM"


class EmailType(str, Enum):
    WELCOME = "WELCOME"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    PASSWORD_RESET = "PASSWORD_RESET"
    APPLICATION_CONFIRMATION = "APPLICATION_CONFIRMATION"
    APPLICATION_STATUS = "APPLICATION_STATUS"
    INTERVIEW_INVITE = "INTERVIEW_INVITE"
    NEW_APPLICATION_RECRUITER = "NEW_APPLICATION_RECRUITER"
    ADMIN = "ADMIN"


class EmailStatus(str, Enum):
    QUEUED = "QUEUED"
    SENT = "SENT"
    FAILED = "FAILED"


class InterviewType(str, Enum):
    TALENDUS = "TALENDUS"
    CLIENT = "CLIENT"
    PHONE = "PHONE"
    VIDEO = "VIDEO"
    ONSITE = "ONSITE"
    OFFER = "OFFER"


class InterviewStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class InvoiceStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    PENDING = "PENDING"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"


class PaymentMethod(str, Enum):
    TRANSFER = "TRANSFER"
    CHEQUE = "CHEQUE"
    CARD = "CARD"
    OTHER = "OTHER"


class BlogStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    SCHEDULED = "SCHEDULED"
    ARCHIVED = "ARCHIVED"


OPEN_JOB_STATUSES = {JobStatus.PUBLISHED}
PUBLIC_JOB_STATUSES = {JobStatus.PUBLISHED, JobStatus.PAUSED}
