"""Catalogue exhaustif des métiers desservis par Talendus."""

from __future__ import annotations

# (sector_key, fr, en)
OCCUPATIONS: tuple[tuple[str, str, str], ...] = (
    # Production
    ("production", "Opérateur de production", "Production operator"),
    ("production", "Opérateur de machine", "Machine operator"),
    ("production", "Opérateur de presse", "Press operator"),
    ("production", "Opérateur CNC", "CNC operator"),
    ("production", "Assembleur / Assembleuse", "Assembler"),
    ("production", "Assembleur électronique", "Electronics assembler"),
    ("production", "Manœuvre de production", "Production labourer"),
    ("production", "Préposé à la ligne", "Line attendant"),
    ("production", "Emballeur / Emballeuse", "Packer"),
    ("production", "Emballeur alimentaire", "Food packer"),
    ("production", "Contrôleur de qualité", "Quality inspector"),
    ("production", "Inspecteur qualité", "Quality control inspector"),
    ("production", "Technicien qualité", "Quality technician"),
    ("production", "Technicien de production", "Production technician"),
    ("production", "Superviseur de production", "Production supervisor"),
    ("production", "Contremaître de production", "Production foreperson"),
    ("production", "Chef d'équipe production", "Production team lead"),
    ("production", "Planificateur de production", "Production planner"),
    ("production", "Régleur de machines", "Machine setter"),
    ("production", "Opérateur de moulage", "Molding operator"),
    ("production", "Opérateur d'injection plastique", "Plastic injection operator"),
    ("production", "Soudeur / Soudeuse", "Welder"),
    ("production", "Soudeur MIG", "MIG welder"),
    ("production", "Soudeur TIG", "TIG welder"),
    ("production", "Tuyauteur / Tuyauteuse", "Pipefitter"),
    ("production", "Ajusteur-monteur", "Fitter-assembler"),
    ("production", "Machiniste", "Machinist"),
    ("production", "Outilleur-ajusteur", "Tool and die maker"),
    ("production", "Opérateur de scie", "Saw operator"),
    ("production", "Opérateur de plieuse", "Press brake operator"),
    ("production", "Opérateur de laser", "Laser operator"),
    ("production", "Peintre industriel", "Industrial painter"),
    ("production", "Sableur / Sableuse", "Sandblaster"),
    ("production", "Polisseur / Polisseuse", "Polisher"),
    ("production", "Opérateur de four", "Furnace operator"),
    ("production", "Opérateur de mélangeur", "Mixer operator"),
    ("production", "Opérateur alimentaire", "Food processing operator"),
    ("production", "Boucher industriel", "Industrial butcher"),
    ("production", "Découpeur de viande", "Meat cutter"),
    ("production", "Opérateur de boulangerie", "Bakery operator"),
    ("production", "Opérateur pharmaceutique", "Pharmaceutical operator"),
    ("production", "Technicien de laboratoire", "Laboratory technician"),
    ("production", "Aide-généraliste usine", "General factory helper"),
    # Entrepôt / logistique
    ("entrepot", "Préposé d'entrepôt", "Warehouse attendant"),
    ("entrepot", "Manutentionnaire", "Material handler"),
    ("entrepot", "Magasinier / Magasinière", "Storekeeper"),
    ("entrepot", "Commis d'entrepôt", "Warehouse clerk"),
    ("entrepot", "Préposé à la réception", "Receiving clerk"),
    ("entrepot", "Préposé à l'expédition", "Shipping clerk"),
    ("entrepot", "Réceptionnaire", "Receiver"),
    ("entrepot", "Expéditeur / Expéditrice", "Shipper"),
    ("entrepot", "Préposé au picking", "Order picker"),
    ("entrepot", "Préposé à la préparation de commandes", "Order picker"),
    ("entrepot", "Emballeur d'entrepôt", "Warehouse packer"),
    ("entrepot", "Opérateur de chariot élévateur", "Forklift operator"),
    ("entrepot", "Cariste", "Reach truck operator"),
    ("entrepot", "Opérateur de transpalette", "Pallet jack operator"),
    ("entrepot", "Opérateur de gerbeur", "Stacker operator"),
    ("entrepot", "Opérateur de pont roulant", "Overhead crane operator"),
    ("entrepot", "Inventoriste", "Inventory clerk"),
    ("entrepot", "Préposé à l'inventaire", "Inventory attendant"),
    ("entrepot", "Superviseur d'entrepôt", "Warehouse supervisor"),
    ("entrepot", "Chef d'équipe entrepôt", "Warehouse team lead"),
    ("entrepot", "Coordonnateur logistique", "Logistics coordinator"),
    ("entrepot", "Répartiteur / Répartitrice", "Dispatcher"),
    ("entrepot", "Planificateur logistique", "Logistics planner"),
    ("entrepot", "Commis à la facturation", "Billing clerk"),
    ("entrepot", "Commis à la documentation", "Documentation clerk"),
    ("entrepot", "Préposé au quai", "Dock attendant"),
    ("entrepot", "Chargeur / Déchargeur", "Loader / unloader"),
    ("entrepot", "Trieur / Trieuse", "Sorter"),
    ("entrepot", "Préposé colis", "Parcel attendant"),
    ("entrepot", "Opérateur de convoyeur", "Conveyor operator"),
    # Métiers spécialisés / maintenance
    ("metiers", "Électricien industriel", "Industrial electrician"),
    ("metiers", "Électricien de construction", "Construction electrician"),
    ("metiers", "Électricien d'entretien", "Maintenance electrician"),
    ("metiers", "Apprenti électricien", "Apprentice electrician"),
    ("metiers", "Mécanicien industriel", "Industrial mechanic"),
    ("metiers", "Mécanicien de millwright", "Millwright"),
    ("metiers", "Millwright", "Millwright"),
    ("metiers", "Apprenti mécanicien industriel", "Apprentice millwright"),
    ("metiers", "Technicien de maintenance", "Maintenance technician"),
    ("metiers", "Préposé à l'entretien", "Maintenance attendant"),
    ("metiers", "Homme à tout faire / Femme à tout faire", "Handyperson"),
    ("metiers", "Concierge", "Janitor / custodian"),
    ("metiers", "Préposé à l'entretien ménager", "Cleaner"),
    ("metiers", "Plombier / Plombière", "Plumber"),
    ("metiers", "Apprenti plombier", "Apprentice plumber"),
    ("metiers", "Frigoriste", "Refrigeration technician"),
    ("metiers", "Technicien CVC / HVAC", "HVAC technician"),
    ("metiers", "Technicien en automatisation", "Automation technician"),
    ("metiers", "Technicien en instrumentation", "Instrumentation technician"),
    ("metiers", "Électromécanicien", "Electromechanic"),
    ("metiers", "Technicien en robotique", "Robotics technician"),
    ("metiers", "Serrurier / Serrurière", "Locksmith"),
    ("metiers", "Menuisier / Menuisière", "Carpenter"),
    ("metiers", "Ébéniste", "Cabinetmaker"),
    ("metiers", "Peintre en bâtiment", "House painter"),
    ("metiers", "Plafonneur / Plafonneuse", "Drywaller"),
    ("metiers", "Carreleur / Carreleuse", "Tiler"),
    ("metiers", "Briqueteur-maçon", "Bricklayer"),
    ("metiers", "Cimentier-applicateur", "Cement finisher"),
    ("metiers", "Ferrailleur / Ferrailleuse", "Rebar worker"),
    ("metiers", "Coffreur / Coffreuse", "Formworker"),
    ("metiers", "Couvreur / Couvreuse", "Roofer"),
    ("metiers", "Vitrier / Vitrière", "Glazier"),
    ("metiers", "Calorifugeur / Calorifugeuse", "Insulator"),
    ("metiers", "Tôlier / Tôlière", "Sheet metal worker"),
    ("metiers", "Chaudronnier / Chaudronnière", "Boilermaker"),
    ("metiers", "Mécanicien de véhicules lourds", "Heavy-duty mechanic"),
    ("metiers", "Mécanicien automobile", "Automotive mechanic"),
    ("metiers", "Débosseleur / Débosseleuse", "Auto body technician"),
    ("metiers", "Technicien en diagnostic auto", "Automotive diagnostic technician"),
    ("metiers", "Soudeur de chantier", "Field welder"),
    ("metiers", "Monteur d'acier", "Ironworker"),
    ("metiers", "Monteur d'échafaudages", "Scaffolder"),
    ("metiers", "Opérateur de nacelle", "Boom lift operator"),
    ("metiers", "Technicien de bâtiments", "Building technician"),
    ("metiers", "Superviseur de maintenance", "Maintenance supervisor"),
    # Transport
    ("transport", "Chauffeur de camion", "Truck driver"),
    ("transport", "Chauffeur classe 1 / AZ", "Class 1 / AZ truck driver"),
    ("transport", "Chauffeur classe 3 / DZ", "Class 3 / DZ truck driver"),
    ("transport", "Chauffeur de camion porteur", "Straight truck driver"),
    ("transport", "Chauffeur de camion-remorque", "Tractor-trailer driver"),
    ("transport", "Chauffeur local", "Local driver"),
    ("transport", "Chauffeur longue distance", "Long-haul driver"),
    ("transport", "Chauffeur-livreur", "Delivery driver"),
    ("transport", "Livreur / Livreuse", "Courier"),
    ("transport", "Chauffeur de fourgonnette", "Van driver"),
    ("transport", "Chauffeur d'autobus", "Bus driver"),
    ("transport", "Chauffeur d'autocar", "Coach driver"),
    ("transport", "Chauffeur de transport adapté", "Paratransit driver"),
    ("transport", "Chauffeur de taxi", "Taxi driver"),
    ("transport", "Chauffeur Uber / Lyft", "Rideshare driver"),
    ("transport", "Chauffeur de limousine", "Limousine driver"),
    ("transport", "Opérateur d'équipement lourd", "Heavy equipment operator"),
    ("transport", "Opérateur de pelle mécanique", "Excavator operator"),
    ("transport", "Opérateur de chargeuse", "Loader operator"),
    ("transport", "Opérateur de grue", "Crane operator"),
    ("transport", "Opérateur de niveleuse", "Grader operator"),
    ("transport", "Camionneur de chantier", "Dump truck driver"),
    ("transport", "Chauffeur de bétonnière", "Concrete mixer driver"),
    ("transport", "Chauffeur de déneigement", "Snowplow driver"),
    ("transport", "Répartiteur transport", "Transport dispatcher"),
    ("transport", "Coordonnateur transport", "Transport coordinator"),
    ("transport", "Aide-chauffeur", "Driver helper"),
    ("transport", "Manoeuvre de camionnage", "Trucking labourer"),
    # Santé
    ("sante", "Préposé aux bénéficiaires (PAB)", "Personal support worker (PSW)"),
    ("sante", "Aide-soignant / Aide-soignante", "Care aide"),
    ("sante", "Infirmier / Infirmière", "Nurse"),
    ("sante", "Infirmier auxiliaire", "Licensed practical nurse"),
    ("sante", "Préposé aux soins", "Care attendant"),
    ("sante", "Préposé à l'entretien en santé", "Healthcare cleaner"),
    ("sante", "Commis d'unité", "Unit clerk"),
    ("sante", "Réceptionniste clinique", "Clinic receptionist"),
    ("sante", "Adjoint administratif santé", "Healthcare administrative assistant"),
    ("sante", "Technicien de laboratoire médical", "Medical lab technician"),
    ("sante", "Préposé à la stérilisation", "Sterilization attendant"),
    ("sante", "Aide de cuisine en établissement", "Institutional kitchen helper"),
    ("sante", "Préposé à la buanderie", "Laundry attendant"),
    ("sante", "Accompagnateur / Accompagnatrice", "Companion / escort"),
    ("sante", "Travailleur de soutien à domicile", "Home support worker"),
    ("sante", "Éducateur / Éducatrice", "Educator"),
    ("sante", "Éducateur spécialisé", "Specialized educator"),
    ("sante", "Intervenant / Intervenante", "Support worker"),
    ("sante", "Travailleur social", "Social worker"),
    ("sante", "Préposé en résidence pour aînés", "Senior residence attendant"),
    # Administration
    ("admin", "Adjoint administratif", "Administrative assistant"),
    ("admin", "Secrétaire", "Secretary"),
    ("admin", "Réceptionniste", "Receptionist"),
    ("admin", "Commis de bureau", "Office clerk"),
    ("admin", "Commis à la saisie", "Data entry clerk"),
    ("admin", "Commis-comptable", "Accounting clerk"),
    ("admin", "Technicien en comptabilité", "Accounting technician"),
    ("admin", "Comptable", "Accountant"),
    ("admin", "Commis paie", "Payroll clerk"),
    ("admin", "Commis RH", "HR clerk"),
    ("admin", "Coordonnateur RH", "HR coordinator"),
    ("admin", "Recruteur / Recruteuse", "Recruiter"),
    ("admin", "Agent de recouvrement", "Collections agent"),
    ("admin", "Commis à la facturation", "Billing clerk"),
    ("admin", "Service à la clientèle", "Customer service representative"),
    ("admin", "Agent de centre d'appels", "Call centre agent"),
    ("admin", "Téléphoniste", "Switchboard operator"),
    ("admin", "Assistant de direction", "Executive assistant"),
    ("admin", "Coordonnateur de projet", "Project coordinator"),
    ("admin", "Acheteur / Acheteuse", "Buyer"),
    ("admin", "Commis aux achats", "Purchasing clerk"),
    ("admin", "Commis à l'approvisionnement", "Supply clerk"),
    ("admin", "Archiviste", "Records clerk"),
    ("admin", "Commis juridique", "Legal clerk"),
    ("admin", "Agent immobilier", "Real estate agent"),
    ("admin", "Courtier d'assurance", "Insurance broker"),
    ("admin", "Agent de voyages", "Travel agent"),
    # Technologie
    ("tech", "Développeur web", "Web developer"),
    ("tech", "Développeur full-stack", "Full-stack developer"),
    ("tech", "Développeur front-end", "Front-end developer"),
    ("tech", "Développeur back-end", "Back-end developer"),
    ("tech", "Programmeur / Programmeuse", "Programmer"),
    ("tech", "Analyste programmeur", "Programmer analyst"),
    ("tech", "Technicien informatique", "IT technician"),
    ("tech", "Technicien helpdesk", "Helpdesk technician"),
    ("tech", "Administrateur réseau", "Network administrator"),
    ("tech", "Administrateur systèmes", "Systems administrator"),
    ("tech", "Analyste en cybersécurité", "Cybersecurity analyst"),
    ("tech", "Analyste de données", "Data analyst"),
    ("tech", "Technicien en support TI", "IT support technician"),
    ("tech", "Intégrateur web", "Web integrator"),
    ("tech", "Designer UX / UI", "UX / UI designer"),
    ("tech", "Graphiste", "Graphic designer"),
    ("tech", "Technicien en télécommunications", "Telecom technician"),
    ("tech", "Installateur de réseaux", "Network installer"),
    ("tech", "Technicien fibre optique", "Fiber optic technician"),
    ("tech", "Chef de projet TI", "IT project manager"),
    ("tech", "Testeur QA", "QA tester"),
    ("tech", "Analyste d'affaires", "Business analyst"),
    # Construction
    ("construction", "Manœuvre de construction", "Construction labourer"),
    ("construction", "Journalier de chantier", "Site labourer"),
    ("construction", "Aide-généraliste chantier", "General construction helper"),
    ("construction", "Charpentier-menuisier", "Carpenter"),
    ("construction", "Monteur de structures", "Structural assembler"),
    ("construction", "Opérateur de compacteur", "Compactor operator"),
    ("construction", "Poseur de cloisons sèches", "Drywall installer"),
    ("construction", "Finisseur de béton", "Concrete finisher"),
    ("construction", "Poseur de planchers", "Flooring installer"),
    ("construction", "Installateur de fenêtres", "Window installer"),
    ("construction", "Installateur de portes", "Door installer"),
    ("construction", "Installateur de cuisine", "Kitchen installer"),
    ("construction", "Paysagiste", "Landscaper"),
    ("construction", "Jardinier / Jardinière", "Gardener"),
    ("construction", "Horticulteur / Horticultrice", "Horticulturist"),
    ("construction", "Déneigeur / Déneigeuse", "Snow removal worker"),
    ("construction", "Préposé à l'entretien extérieur", "Groundskeeper"),
    ("construction", "Surveillant de chantier", "Site supervisor"),
    ("construction", "Contremaître de chantier", "Construction foreperson"),
    ("construction", "Estimateur en construction", "Construction estimator"),
    ("construction", "Dessinateur de plans", "Drafter"),
    ("construction", "Arpenteur-géomètre", "Surveyor"),
    ("construction", "Aide-arpenteur", "Survey assistant"),
    # Restauration / hôtellerie / commerce
    ("resto", "Cuisinier / Cuisinière", "Cook"),
    ("resto", "Chef cuisinier", "Chef"),
    ("resto", "Sous-chef", "Sous-chef"),
    ("resto", "Aide-cuisinier", "Cook's helper"),
    ("resto", "Commis de cuisine", "Kitchen helper"),
    ("resto", "Plongeur / Plongeuse", "Dishwasher"),
    ("resto", "Serveur / Serveuse", "Server"),
    ("resto", "Hôte / Hôtesse", "Host / hostess"),
    ("resto", "Barista", "Barista"),
    ("resto", "Barman / Barmaid", "Bartender"),
    ("resto", "Caissier / Caissière", "Cashier"),
    ("resto", "Commis d'épicerie", "Grocery clerk"),
    ("resto", "Commis de magasin", "Store clerk"),
    ("resto", "Vendeur / Vendeuse", "Sales associate"),
    ("resto", "Conseiller vente", "Sales advisor"),
    ("resto", "Représentant des ventes", "Sales representative"),
    ("resto", "Préposé à la boucherie", "Butcher shop attendant"),
    ("resto", "Préposé à la boulangerie", "Bakery attendant"),
    ("resto", "Préposé aux fruits et légumes", "Produce clerk"),
    ("resto", "Préposé à la viande", "Meat department attendant"),
    ("resto", "Gérant de magasin", "Store manager"),
    ("resto", "Superviseur de plancher", "Floor supervisor"),
    ("resto", "Préposé à l'accueil", "Front desk attendant"),
    ("resto", "Réceptionniste d'hôtel", "Hotel receptionist"),
    ("resto", "Femme / Valet de chambre", "Room attendant"),
    ("resto", "Gouvernant / Gouvernante", "Housekeeping supervisor"),
    ("resto", "Préposé à l'entretien hôtel", "Hotel cleaner"),
    ("resto", "Bagagiste", "Bellhop"),
    ("resto", "Préposé au vestiaire", "Coat check attendant"),
    ("resto", "Commis traiteur", "Catering clerk"),
    ("resto", "Livreur de repas", "Food delivery driver"),
    # Autre
    ("autre", "Agent de sécurité", "Security guard"),
    ("autre", "Agent de surveillance", "Surveillance agent"),
    ("autre", "Gardien d'immeuble", "Building superintendent"),
    ("autre", "Concierge d'immeuble", "Building concierge"),
    ("autre", "Préposé au stationnement", "Parking attendant"),
    ("autre", "Préposé à la collecte", "Waste collector"),
    ("autre", "Éboueur / Éboueuse", "Garbage collector"),
    ("autre", "Opérateur d'usine de traitement", "Treatment plant operator"),
    ("autre", "Technicien en environnement", "Environmental technician"),
    ("autre", "Préposé aux animaux", "Animal attendant"),
    ("autre", "Coiffeur / Coiffeuse", "Hairdresser"),
    ("autre", "Esthéticien / Esthéticienne", "Esthetician"),
    ("autre", "Technicien dentaire", "Dental technician"),
    ("autre", "Photographe", "Photographer"),
    ("autre", "Monteur vidéo", "Video editor"),
    ("autre", "Animateur / Animatrice", "Animator / host"),
    ("autre", "Formateur / Formatrice", "Trainer"),
    ("autre", "Enseignant / Enseignante", "Teacher"),
    ("autre", "Surveillant d'élèves", "School supervisor"),
    ("autre", "Préposé à la bibliothèque", "Library attendant"),
    ("autre", "Aide-déménageur", "Mover's helper"),
    ("autre", "Déménageur / Déménageuse", "Mover"),
    ("autre", "Manœuvre général", "General labourer"),
    ("autre", "Autre métier", "Other occupation"),
)

SECTOR_LABELS = {
    "production": ("Production", "Production"),
    "entrepot": ("Entrepôt et logistique", "Warehouse and logistics"),
    "metiers": ("Métiers spécialisés", "Skilled trades"),
    "transport": ("Transport", "Transport"),
    "sante": ("Santé et services", "Health and services"),
    "admin": ("Administration", "Administration"),
    "tech": ("Technologie", "Technology"),
    "construction": ("Construction", "Construction"),
    "resto": ("Restauration et commerce", "Hospitality and retail"),
    "autre": ("Autre", "Other"),
}


def occupation_choices() -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for sector, fr, en in OCCUPATIONS:
        key = fr.strip()
        if key in seen:
            continue
        seen.add(key)
        group_fr, group_en = SECTOR_LABELS.get(sector, ("Autre", "Other"))
        out.append(
            {
                "value": key,
                "label": fr,
                "label_en": en,
                "group": group_fr,
                "group_en": group_en,
                "sector": sector,
            }
        )
    return out
