"""Hubs messagerie / 3PL / CD — genre Purolator (trieurs, caristes, quais, nuit).

Courriels uniquement s’ils ont été vus sur une page publique officielle
(ou page LinkedIn **entreprise** qui les publie elle-même).
Aucune adresse déduite du prénom.
"""

from __future__ import annotations

# Présence : catalogue = fiche quebec_employer_leads ; indeed = veille Indeed QC ;
# nouveau = pas encore au catalogue.

HUBS: list[dict] = [
    {
        "name": "Purolator",
        "presence": "catalogue",
        "website": "https://www.purolator.com",
        "city": "Saint-Laurent",
        "sector": "Messagerie / hubs colis",
        "employees": 12000,
        "activity": "Réseau pancanadien de colis, hubs Grand Montréal (Saint-Laurent, Boucherville) et Québec",
        "hiring_signal": "Offres publiques trieurs / préposés d’entrepôt et mécanicien classe A ; recrutement réseau en continu",
        "offers": 3,
        "roles": "Trieur AM Saint-Laurent / Boucherville ; préposé d’entrepôt / dock ; mécanicien classe A (quart soir)",
        "shift": "Jour, soir, tri tôt le matin",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "TalentCOE@purolator.com",
                "kind": "recrutement",
                "who": "Talent COE (questions IA recrutement + programme coop)",
                "proof": "careers.purolator.com — « For AI-related inquiries only, contact TalentCOE@purolator.com » + page Co-op « send an email to TalentCOE@purolator.com »",
            },
            {
                "addr": "david.bauer@purolator.com",
                "kind": "media",
                "who": "Dave Bauer, Head of Corporate Communications (articles officiels)",
                "proof": "Articles officiels purolator.com (investissement 1 G$ / 1 100 emplois) — « david.bauer@purolator.com »",
            },
        ],
        "phone": "",
        "address": "Réseau QC — hubs Montréal / Saint-Laurent / Boucherville ; 7000, rue Armand-Viau (Québec)",
        "src_co": "https://www.purolator.com + https://careers.purolator.com/",
        "src_job": "https://careers.purolator.com/ — offres trieurs / dock / mécanicien QC",
        "src_person": "Dave Bauer nommé sur les communiqués officiels purolator.com",
        "src_email": "Portail carrières officiel (TalentCOE@) + articles médias officiels (david.bauer@). Pas d’inbox rh@ / jobs@ Montréal publiée — candidatures via le portail.",
        "confidence": "Élevé sur TalentCOE@ (page carrières actuelle). Moyen sur david.bauer@ (publié, rôle médias, peut dater).",
        "why": "C’est exactement le profil demandé : hubs colis GMA qui embauchent trieurs et dock en continu. Exclu à tort de la 1re passe parce qu’il était déjà au catalogue.",
        "angle": "Ne pas écrire à TalentCOE@ pour placer des trieurs (boîte IA/coop). Utiliser le portail + relance médias/ops locale. Offrir un bassin trieurs/caristes quarts tôt / soir Saint-Laurent–Boucherville.",
        "notes": "2 emails officiels. Aucune inbox « recrutement trieurs Montréal » type rh@ n’est publiée. Les emails trouvés par une recherche simple sont surtout TalentCOE@, comm. corp. et médias — pas une boîte TA locale.",
    },
    {
        "name": "Intelcom | Dragonfly",
        "presence": "catalogue",
        "website": "https://intelcom.ca",
        "city": "Montréal",
        "sector": "Messagerie last-mile / stations de tri",
        "employees": 500,
        "activity": "Leader last-mile QC, 100+ stations de tri, sièges 1380 William, stations Candiac / Laval / Montréal",
        "hiring_signal": "Trieurs de colis / commis d’entrepôt Candiac, Laval, Montréal — dont sur appel et quarts tôt le matin",
        "offers": 4,
        "roles": "Trieur(euse) de colis ; commis d’entrepôt PM ; trieur sur appel ; livreurs",
        "shift": "Jour, PM, tôt le matin (ex. 3 h)",
        "ops_roles": True,
        "night_shift": True,
        "growth": True,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": False,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "contact@intelcomexpress.com",
                "kind": "general",
                "who": "Service à la clientèle (schema.org officiel)",
                "proof": "JSON-LD officiel intelcom.ca et dragonflyshipping.ca — contactPoint.email",
            },
            {
                "addr": "info@intelcomexpress.com",
                "kind": "general",
                "who": "",
                "proof": "Site officiel intelcom.ca/fr/ (enrichissement catalogue)",
            },
        ],
        "phone": "1-833-640-2301",
        "address": "1380, rue William, Montréal (QC) H3C 1R5",
        "src_co": "https://intelcom.ca/en/careers/ + https://dragonflyshipping.ca/",
        "src_job": "Offres trieurs Candiac / Laval / Montréal (Indeed + Espresso-Jobs, sept. 2026)",
        "src_person": "",
        "src_email": "Schema.org officiel (contact@) + accueil officiel (info@). Portail carrières sans inbox RH dédiée.",
        "confidence": "Élevé sur les 2 boîtes. Recrutement ops via ATS / Indeed, pas via ces inbox.",
        "why": "Le plus proche jumeau québécois de Purolator pour les trieurs : stations locales, quarts 3 h du matin, volume récurrent.",
        "angle": "Bassin trieurs/commis d’entrepôt multi-stations (Candiac, Laval, Montréal) — dispo tôt le matin.",
        "notes": "2 emails vérifiables. Fiche catalogue = Intelcom.",
    },
    {
        "name": "GLS Canada",
        "presence": "catalogue",
        "website": "https://www.gls-canada.com",
        "city": "Dorval",
        "sector": "Messagerie / tri de colis",
        "employees": 400,
        "activity": "Réseau colis QC, hub 10755 Côte-de-Liesse (Dorval)",
        "hiring_signal": "Offre publique « Trieur de colis – nuit » Dorval, 23h–5h30",
        "offers": 2,
        "roles": "Trieur de colis nuit ; livreurs / messagerie",
        "shift": "Nuit 23h–5h30",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "recrutement@gls-canada.com",
                "kind": "recrutement",
                "who": "",
                "proof": "Page carrières officielle GLS Canada + offre trieur nuit — recrutement@gls-canada.com",
            },
        ],
        "phone": "",
        "address": "10755, chemin de la Côte-de-Liesse, Dorval (QC)",
        "src_co": "https://gls-group.com/CA/en/careers/",
        "src_job": "Offre Trieur de colis – nuit, Dorval (publiée sur le canal carrières GLS)",
        "src_person": "",
        "src_email": "Site officiel carrières GLS Canada",
        "confidence": "Élevé — meilleure inbox recrutement du corpus messagerie GMA",
        "why": "Inbox recrutement publiée + tri de nuit Dorval. C’est le contact le plus actionnable du genre Purolator.",
        "angle": "Écrire à recrutement@ avec un bassin trieurs nuit Ouest-de-l’Île / Dorval.",
        "notes": "1 email RH/recrutement réel. Rare chez les nationaux.",
    },
    {
        "name": "Loomis Express",
        "presence": "catalogue",
        "website": "https://www.loomis-express.com",
        "city": "Montréal",
        "sector": "Messagerie / quai",
        "employees": 800,
        "activity": "Messagerie nationale (TFI), quais et livreurs QC",
        "hiring_signal": "Page carrières : CV à careers@ ; embauches warehouse / owner-operator sur le réseau",
        "offers": 2,
        "roles": "Préposé d’entrepôt / quai ; chauffeurs / owner-operator ; messagerie",
        "shift": "Quais multi-quarts (typique messagerie)",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "careers@loomis-express.com",
                "kind": "recrutement",
                "who": "",
                "proof": "Page officielle loomis-express.com/loomship/Home/Careers — « click here (careers@loomis-express.com) to submit a resume »",
            },
        ],
        "phone": "1-855-256-6647",
        "address": "Opérations QC (TFI International)",
        "src_co": "https://www.loomis-express.com/loomship/Home/Careers",
        "src_job": "Même page carrières — CV par courriel, indiquer poste + lieu",
        "src_person": "",
        "src_email": "Page Carrières officielle Loomis Express",
        "confidence": "Élevé — inbox carrières publiée",
        "why": "Messagerie TFI qui accepte encore les CV par courriel (pas seulement un ATS).",
        "angle": "CV quais / warehouse GMA à careers@ avec objet « Warehouse – Montréal ».",
        "notes": "1 email recrutement. Taille nationale : recrutement plus centralisé.",
    },
    {
        "name": "Canpar Express",
        "presence": "catalogue",
        "website": "https://www.canpar.com",
        "city": "Montréal",
        "sector": "Messagerie / colis",
        "employees": 1700,
        "activity": "Colis TFI, 55 terminaux, opérations QC",
        "hiring_signal": "Page carrières + job fairs ; CV demandés à recruitment@",
        "offers": 2,
        "roles": "Messagerie, quai, chauffeurs, owner-operator",
        "shift": "Quais / routes (multi-quarts typiques)",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "recruitment@canpar.com",
                "kind": "recrutement",
                "who": "",
                "proof": "Publications LinkedIn officielles Canpar Express (job fairs 2025–2026) — « email your resume to recruitment@canpar.com »",
            },
            {
                "addr": "customerservice@canpar.com",
                "kind": "general",
                "who": "",
                "proof": "Page confidentialité officielle canpar.com/en/about/privacy.htm",
            },
        ],
        "phone": "",
        "address": "Terminaux QC (réseau national)",
        "src_co": "https://www.canpar.com/en/careers/careers.htm",
        "src_job": "Page carrières Canpar + posts LinkedIn entreprise",
        "src_person": "",
        "src_email": "LinkedIn entreprise officiel (recruitment@) + privacy officielle (customerservice@)",
        "confidence": "Élevé sur customerservice@ ; élevé-moyen sur recruitment@ (publié par la page entreprise, pas le site HTML)",
        "why": "Sœur TFI de Loomis — mêmes quais colis, inbox recrutement publiée.",
        "angle": "CV quais / chauffeurs GMA à recruitment@.",
        "notes": "2 emails. recruitment@ vu sur LinkedIn entreprise, pas sur le HTML careers.htm.",
    },
    {
        "name": "UPS Canada",
        "presence": "catalogue",
        "website": "https://www.ups.com",
        "city": "Lachine",
        "sector": "Messagerie / hub de tri",
        "employees": 8000,
        "activity": "Hub Lachine (1221, 32e Avenue) — tri jour / import / soir",
        "hiring_signal": "Package Handler Day Sort, Import, quarts flexibles Lachine — offres 2026",
        "offers": 3,
        "roles": "Package handler (tri jour, import, soir) ; ingénierie système de tri (nuit)",
        "shift": "Jour 12h–18h ; soir 15h–22h30 ; nuit 0h–8h30 (ingénierie tri)",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "mediarelations@ups.com",
                "kind": "media",
                "who": "Relations médias UPS Canada",
                "proof": "Salle de presse officielle The UPS Store Canada — « UPS Canada : mediarelations@ups.com »",
            },
            {
                "addr": "pr@ups.com",
                "kind": "media",
                "who": "Media Relations UPS (newsroom mondial)",
                "proof": "about.ups.com/us/en/newsroom.html — « Media Relations (pr@ups.com) »",
            },
        ],
        "phone": "",
        "address": "1221, 32e Avenue, Lachine (QC) H8T 3H2",
        "src_co": "https://www.jobs-ups.com/ + https://about.ups.com/us/en/newsroom.html",
        "src_job": "Offres Package Handler Lachine (portail UPS 2026)",
        "src_person": "",
        "src_email": "Newsrooms officielles. Aucune inbox RH/trieurs publique — portail only.",
        "confidence": "Élevé sur les 2 boîtes médias. Nulle sur un contact TA local.",
        "why": "Hub de tri Lachine qui embauche des package handlers en continu (jour/soir/nuit). Même métier que trieur Purolator.",
        "angle": "Ne pas spammer pr@. Approche : bassin package handlers Lachine + portail. Contact TA seulement s’ils répondent au portail.",
        "notes": "2 emails médias. Zéro inbox recrutement. C’est normal : UPS est 100 % ATS.",
    },
    {
        "name": "FedEx",
        "presence": "catalogue",
        "website": "https://www.fedex.com",
        "city": "Montréal-Est",
        "sector": "Messagerie / hub de tri",
        "employees": 6000,
        "activity": "Hub 8481, place Marien (Montréal-Est) + ops Dorval",
        "hiring_signal": "Package Handler / Non-Driver, Sort Manager, Package Handler Trainer — Montréal-Est",
        "offers": 3,
        "roles": "Package handler (tri 2h–10h) ; sort manager ; formateur package handlers",
        "shift": "Nuit / tôt le matin (ex. sam–mer 2h–10h ; formateur 4h–11h)",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "mediarelations@fedex.com",
                "kind": "media",
                "who": "FedEx Media Relations US & Canada",
                "proof": "newsroom.fedex.com/media-requests-and-resources — « email mediarelations@fedex.com »",
            },
        ],
        "phone": "",
        "address": "8481, place Marien, Montréal-Est (QC) H1B 5W6",
        "src_co": "https://careers.fedex.com/",
        "src_job": "https://careers.fedex.com/package-handler-non-driver-warehouse-like/job/P25-93318-6",
        "src_person": "",
        "src_email": "Newsroom officiel. Portail carrières sans inbox RH publique.",
        "confidence": "Élevé sur l’email médias. Nulle sur TA locale.",
        "why": "Hub Montréal-Est qui trie la nuit — même besoin que Purolator Saint-Laurent.",
        "angle": "Bassin package handlers nuit Montréal-Est. Candidatures via careers.fedex.com seulement.",
        "notes": "1 email médias. Pas de rh@ / jobs@ Canada publié.",
    },
    {
        "name": "DHL Express",
        "presence": "catalogue",
        "website": "https://www.dhl.com",
        "city": "Lachine",
        "sector": "Messagerie express / aéroport",
        "employees": 1500,
        "activity": "Hubs express Dorval / Lachine, TA Canada basée Lachine",
        "hiring_signal": "Coordonnateur TA bilingue Lachine (2026) ; ops quai / aéroport",
        "offers": 1,
        "roles": "Messagerie, quai, opérations aéroport ; TA interne Lachine",
        "shift": "Quais / aéroport (quarts)",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Lachine / Dorval (QC)",
        "src_co": "https://careers.dhl.com/",
        "src_job": "Offre Bilingual Talent Acquisition Coordinator, Lachine (2026)",
        "src_person": "Nicole Menzies, Sr Manager TA & TM (LinkedIn personnel — email non publié)",
        "src_email": "Aucun courriel RH public. ada@dhl.com = accommodements seulement, non retenu comme contact prospection.",
        "confidence": "Moyen sur le signal TA Lachine ; faible sur le contact",
        "why": "Ils ont une équipe TA à Lachine — donc ils embauchent du volume ops. Contact = portail.",
        "angle": "Ne pas inventer hr@dhl.com. Approche via l’offre TA / LinkedIn entreprise.",
        "notes": "0 email prospection. Portail only.",
    },
    {
        "name": "Postes Canada",
        "presence": "catalogue",
        "website": "https://www.canadapost-postescanada.ca",
        "city": "Montréal",
        "sector": "Messagerie / usines de tri",
        "employees": 50000,
        "activity": "Usines de tri et dépôts QC, recrutement de masse",
        "hiring_signal": "Portail emplois officiel — métiers d’entrepôt, tri, livraison, quarts",
        "offers": 3,
        "roles": "Préposé au tri ; factrice/facteur ; métiers d’entrepôt",
        "shift": "Quarts usine de tri (jour/soir/nuit)",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "media@canadapost.ca",
                "kind": "media",
                "who": "Centre des médias",
                "proof": "Centre des médias officiel canadapost-postescanada.ca",
            },
        ],
        "phone": "",
        "address": "Usines de tri et dépôts QC",
        "src_co": "https://www.canadapost-postescanada.ca",
        "src_job": "Portail emplois officiel Postes Canada",
        "src_person": "",
        "src_email": "Centre des médias officiel. Recrutement = portail seulement.",
        "confidence": "Élevé sur media@. Nulle sur RH.",
        "why": "Usines de tri QC — volume trieurs énorme, mais recrutement 100 % centralisé.",
        "angle": "Priorité basse pour un 1er contact commercial (fédéral, ATS). Utile comme benchmark volume.",
        "notes": "1 email médias. Pas d’inbox RH publique.",
    },
    {
        "name": "Nationex",
        "presence": "nouveau",
        "website": "https://nationex.com",
        "city": "Saint-Hubert",
        "sector": "Messagerie québécoise / colis",
        "employees": 400,
        "activity": "Messagerie 100 % québécoise (1980), 22 dépôts, siège 3505 boul. Losch, Saint-Hubert",
        "hiring_signal": "Historique d’offres manutentionnaire soir/nuit Saint-Hubert ; page Carrières active",
        "offers": 1,
        "roles": "Manutentionnaire soir et nuit ; service à la clientèle ; développement des affaires GMA",
        "shift": "Soir et nuit (offres LinkedIn entreprise 2020 — à reconfirmer sur le portail actuel)",
        "ops_roles": True,
        "night_shift": True,
        "growth": True,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "carrieres@nationex.com",
                "kind": "recrutement",
                "who": "",
                "proof": "Publications LinkedIn officielles de l’entreprise Nationex (2020–2021) — « PAR COURRIEL : carrieres@nationex.com » (manutentionnaire soir/nuit Saint-Hubert, SC, DA GMA)",
            },
        ],
        "phone": "514-861-3453",
        "address": "3505, boulevard Losch, Saint-Hubert (QC) J3Y 5T7",
        "src_co": "https://nationex.com/pages/carrieres + LinkedIn entreprise Nationex",
        "src_job": "Posts LinkedIn entreprise 2020 (manutentionnaire soir/nuit Saint-Hubert)",
        "src_person": "",
        "src_email": "LinkedIn entreprise (2020–2021). La page Carrières actuelle est un formulaire JS — email non visible dans le HTML 2026.",
        "confidence": "Moyen — boîte publiée par l’entreprise, mais posts anciens. Reconfirmer avant 1er envoi.",
        "why": "Jumeau québécois de Purolator : colis, Saint-Hubert, manutentionnaires nuit. Absent du catalogue.",
        "angle": "Tester carrieres@ avec un bassin manutentionnaires soir/nuit Rive-Sud. Si bounce → formulaire site.",
        "notes": "1 email d’entreprise daté 2020–2021. Pas réinventé : publié par Nationex. Reconfirmer.",
    },
    {
        "name": "ICS Courier",
        "presence": "nouveau",
        "website": "https://www.icscourier.ca",
        "city": "Dorval",
        "sector": "Messagerie / tri de colis",
        "employees": 1200,
        "activity": "Messagerie TFI (1978), 35 terminaux, tri Dorval / Laval / Québec",
        "hiring_signal": "Commis au triage Dorval ; trieur de colis nuit Québec (23h30–8h) ; ops Laval",
        "offers": 2,
        "roles": "Commis au triage / mail sorter ; trieur de petit colis nuit ; suivi des opérations",
        "shift": "Soir, nuit (ex. 23h30–8h), 4 h",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Dorval / Laval (QC)",
        "src_co": "https://www.icscourier.ca/ics-careers.aspx",
        "src_job": "Offres commis au triage Dorval + trieur nuit Québec (agrégateurs 2026)",
        "src_person": "",
        "src_email": "Aucun courriel public assez fiable. Page carrières = portail. Un prénom@ dans une offre tierce n’est pas retenu.",
        "confidence": "Moyen sur le volume tri ; faible sur le contact",
        "why": "Même métier que Purolator/GLS : trieurs nuit Dorval. Groupe TFI.",
        "angle": "Candidatures via icscourier.ca/ics-careers. Ne pas inventer careers@icscourier.ca.",
        "notes": "0 email. Portail only.",
    },
    {
        "name": "Groupe Fastfrate",
        "presence": "nouveau",
        "website": "https://www.fastfrate.com",
        "city": "Lachine",
        "sector": "Transport LTL / quai / last-mile",
        "employees": 900,
        "activity": "LTL, entreposage, final mile, terminal Lachine — quai tous terminaux",
        "hiring_signal": "Travailleur de quai (tous les terminaux) + commis facturation Lachine (mardi–samedi)",
        "offers": 2,
        "roles": "Travailleur de quai ; commis facturation Lachine ; manutention ; chauffeurs",
        "shift": "Quai multi-sites ; bureau Lachine mardi–samedi",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "careers@www.fastfrate.com",
                "kind": "recrutement",
                "who": "",
                "proof": "Page officielle fastfrate.com/en/carrieres/ — « curriculum vitae à careers@www.fastfrate.com » (domaine email tel que publié)",
            },
        ],
        "phone": "",
        "address": "Terminal Lachine (QC) — siège Woodbridge (ON)",
        "src_co": "https://www.fastfrate.com/en/carrieres/",
        "src_job": "Travailleur de quai (tous terminaux) + Billing Clerk Lachine",
        "src_person": "",
        "src_email": "Page carrières officielle. Adresse telle quelle (careers@www.fastfrate.com).",
        "confidence": "Élevé — publié sur la page carrières. Format de domaine inhabituel, à tester.",
        "why": "Quais Lachine + last-mile : même bassin caristes/manutentionnaires que les messageries.",
        "angle": "CV travailleurs de quai Lachine à careers@www.fastfrate.com, objet + lieu.",
        "notes": "1 email tel que publié. Ne pas « corriger » en careers@fastfrate.com.",
    },
    {
        "name": "Groupe Robert",
        "presence": "catalogue",
        "website": "https://robert.ca",
        "city": "Montréal",
        "sector": "Transport / entreposage",
        "employees": 2000,
        "activity": "Un des plus grands transporteurs QC — chauffeurs, caristes, journaliers d’entrepôt",
        "hiring_signal": "Recrutement récurrent chauffeurs, caristes, dock, mécaniciens",
        "offers": 3,
        "roles": "Chauffeurs ; caristes ; journaliers d’entrepôt ; mécaniciens",
        "shift": "Quais / routes (multi-quarts)",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "cv@robert.ca",
                "kind": "recrutement",
                "who": "",
                "proof": "Centre de recrutement officiel robert.ca/fr/postes/1",
            },
        ],
        "phone": "",
        "address": "Réseau QC",
        "src_co": "https://robert.ca",
        "src_job": "https://robert.ca/fr/postes/1",
        "src_person": "",
        "src_email": "Site officiel — centre de recrutement",
        "confidence": "Élevé",
        "why": "Gros employeur QC caristes/dock — inbox CV publiée.",
        "angle": "Bassin caristes / journaliers d’entrepôt à cv@robert.ca.",
        "notes": "1 email recrutement.",
    },
    {
        "name": "Day & Ross",
        "presence": "catalogue",
        "website": "https://www.dayross.com",
        "city": "Montréal",
        "sector": "Transport LTL / quai",
        "employees": 1500,
        "activity": "LTL, terminaux QC, chauffeurs et dock",
        "hiring_signal": "Portail carrières — chauffeurs et quai",
        "offers": 1,
        "roles": "Chauffeurs ; quai ; mécaniciens",
        "shift": "Quai / routes",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "sales@dayross.com",
                "kind": "general",
                "who": "Équipe ventes (pas RH)",
                "proof": "Site officiel dayross.com/evolution",
            },
        ],
        "phone": "",
        "address": "Terminaux QC",
        "src_co": "https://www.dayross.com/careers",
        "src_job": "Portail carrières Day & Ross",
        "src_person": "",
        "src_email": "Site officiel ventes. Pas d’inbox RH publique.",
        "confidence": "Élevé sur sales@ ; nulle sur RH",
        "why": "Terminaux LTL QC — quais. Contact RH = portail.",
        "angle": "Ne pas pitcher sales@. Utiliser le portail carrières.",
        "notes": "1 email ventes seulement.",
    },
    {
        "name": "CEVA Logistics",
        "presence": "catalogue",
        "website": "https://www.cevalogistics.com",
        "city": "Montréal",
        "sector": "3PL / logistique contractuelle",
        "employees": 2000,
        "activity": "Logistique contractuelle, entrepôts QC",
        "hiring_signal": "Portail CEVA — entrepôt, transit, opérations",
        "offers": 1,
        "roles": "Entrepôt ; transit ; opérations",
        "shift": "Entrepôt (quarts selon site)",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "CanadaHR@cevalogistics.com",
                "kind": "rh",
                "who": "RH Canada",
                "proof": "Plan d’accessibilité officiel CEVA Canada 2025",
            },
        ],
        "phone": "",
        "address": "Présence QC",
        "src_co": "https://www.cevalogistics.com/en/careers",
        "src_job": "Portail CEVA",
        "src_person": "",
        "src_email": "PDF officiel accessibilité Canada",
        "confidence": "Élevé — boîte RH Canada publiée",
        "why": "3PL avec inbox RH Canada réelle.",
        "angle": "Caristes / commis d’entrepôt QC à CanadaHR@.",
        "notes": "1 email RH Canada.",
    },
    {
        "name": "DSV",
        "presence": "catalogue",
        "website": "https://www.dsv.com",
        "city": "Saint-Laurent",
        "sector": "3PL / transit / entrepôt",
        "employees": 2500,
        "activity": "Bureaux et entrepôts Saint-Laurent, Pointe-Claire, Vaudreuil-Dorion — 73 offres CA dont ~44 GMA",
        "hiring_signal": "Volume d’offres CA élevé (Vaudreuil, Saint-Laurent, Pointe-Claire) + poste TA Saint-Laurent",
        "offers": 5,
        "roles": "Entrepôt ; transitaires ; opérations ; talent acquisition Saint-Laurent",
        "shift": "Entrepôt / bureau",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "HR@ca.dsv.com",
                "kind": "rh",
                "who": "RH Canada (alerte fraude / légitimité des offres)",
                "proof": "Pied de page officiel des offres jobs.dsv.com — « reach out to HR@ca.dsv.com »",
            },
        ],
        "phone": "",
        "address": "Saint-Laurent / Pointe-Claire / Vaudreuil-Dorion (QC)",
        "src_co": "https://www.dsv.com/en-ca/careers",
        "src_job": "https://www.dsv.com/en-ca/careers/job-search — 73 postes Canada",
        "src_person": "",
        "src_email": "Offres officielles DSV Canada (bloc FRAUD ALERT)",
        "confidence": "Élevé — publié sur chaque offre CA. Boîte de vérification plus que de candidature.",
        "why": "Gros 3PL GMA avec entrepôts Vaudreuil/Saint-Laurent et une TA sur place.",
        "angle": "Candidatures via jobs.dsv.com. HR@ seulement pour un contact RH Canada légitime, pas pour spammer des CV.",
        "notes": "1 email RH Canada. Recrutement = portail.",
    },
    {
        "name": "Kuehne+Nagel",
        "presence": "catalogue",
        "website": "https://www.kuehne-nagel.com",
        "city": "Montréal",
        "sector": "3PL / douane / entrepôt",
        "employees": 1800,
        "activity": "Logistique internationale, bureaux et entrepôts QC",
        "hiring_signal": "Portail jobs.kuehne-nagel.com/ca — entrepôt, courtage, ops",
        "offers": 1,
        "roles": "Courtage ; entrepôt ; opérations douanières",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Bureaux et entrepôts QC",
        "src_co": "https://jobs.kuehne-nagel.com/ca/en/home",
        "src_job": "Portail KN Canada — candidatures en ligne seulement (FAQ officielle)",
        "src_person": "",
        "src_email": "Aucun courriel RH public. FAQ : « we only accept online applications ».",
        "confidence": "Élevé sur l’absence d’email (FAQ officielle)",
        "why": "3PL présent QC. Contact = portail.",
        "angle": "Ne pas inventer hr.canada@.",
        "notes": "0 email. Portail only — confirmé par leur FAQ.",
    },
    {
        "name": "TFI International",
        "presence": "catalogue",
        "website": "https://tfiintl.com",
        "city": "Saint-Laurent",
        "sector": "Groupe transport / messagerie",
        "employees": 25000,
        "activity": "Siège 8801 Transcanadienne, bureau 500 — holding de Loomis, Canpar, ICS, etc.",
        "hiring_signal": "Recrutement via les filiales (Loomis, Canpar, ICS) plus que le holding",
        "offers": 0,
        "roles": "RH / ops via filiales messagerie",
        "shift": "",
        "ops_roles": False,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "Alain Bédard",
        "title1": "Président du conseil, président et chef de la direction",
        "li1": "",
        "emails": [
            {
                "addr": "DPO@tfiintl.com",
                "kind": "general",
                "who": "Agent de protection des données",
                "proof": "Page contact officielle tfiintl.com/fr/contact/ — DPO@",
            },
        ],
        "phone": "",
        "address": "8801, route Transcanadienne, bureau 500, Saint-Laurent (QC) H4S 1Z6",
        "src_co": "https://tfiintl.com/fr/contact/",
        "src_job": "https://jobs.tfiintl.com/",
        "src_person": "Page contact officielle — Alain Bédard (abedard@ publié ; non recopié ici comme cible prospection)",
        "src_email": "Page contact officielle. Pas d’inbox RH. Formulaire « Human resources ».",
        "confidence": "Élevé sur DPO@. Nulle sur RH.",
        "why": "Maison-mère des messageries TFI. Mieux contacter Loomis/Canpar/ICS.",
        "angle": "Ne pas écrire au PDG. Passer par careers@ des filiales.",
        "notes": "1 email conformité. abedard@ / dsaperstein@ / jlanglois@ sont publiés (IR) — pas des cibles recrutement.",
    },
    {
        "name": "Groupe Guilbault",
        "presence": "catalogue",
        "website": "https://www.groupeguilbault.com",
        "city": "Boucherville",
        "sector": "Transport / entreposage",
        "employees": 800,
        "activity": "Transport et entreposage (Québec, Boucherville, Saint-Georges)",
        "hiring_signal": "Caristes, entreposeurs, chauffeurs, mécanique — service recrutement publié",
        "offers": 2,
        "roles": "Caristes ; entreposeurs ; chauffeurs ; mécanique",
        "shift": "Entrepôt / routes",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "rh@groupeguilbault.com",
                "kind": "rh",
                "who": "Service recrutement",
                "proof": "Fiche catalogue / site carrières — service recrutement rh@groupeguilbault.com",
            },
        ],
        "phone": "",
        "address": "Boucherville / Québec / Saint-Georges",
        "src_co": "https://www.groupeguilbault.com",
        "src_job": "Page carrières Groupe Guilbault",
        "src_person": "",
        "src_email": "Site / fiche catalogue (rh@ publié)",
        "confidence": "Élevé",
        "why": "PME/mid-market QC qui embauche caristes — inbox RH réelle.",
        "angle": "Bassin caristes / entreposeurs Boucherville à rh@.",
        "notes": "1 email RH.",
    },
    {
        "name": "Transport L.F.L.",
        "presence": "catalogue",
        "website": "https://transportlfl.com",
        "city": "Montréal",
        "sector": "Transport",
        "employees": 200,
        "activity": "Transporteur QC, RH nommée sur le site",
        "hiring_signal": "Page qui-nous-sommes — directrice RH publiée",
        "offers": 1,
        "roles": "Chauffeurs ; ops transport",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "need_score": 3,
        "person1": "Lindsay Longchamps",
        "title1": "Directrice RH et conformité",
        "li1": "",
        "emails": [
            {
                "addr": "lindsay.longchamps@transportlfl.com",
                "kind": "direct",
                "who": "Lindsay Longchamps, directrice RH et conformité",
                "proof": "Site officiel transportlfl.com/qui-nous-sommes/ — courriel publié (pas déduit)",
            },
        ],
        "phone": "",
        "address": "Québec / Grand Montréal",
        "src_co": "https://transportlfl.com/qui-nous-sommes/",
        "src_job": "",
        "src_person": "Page officielle — Lindsay Longchamps",
        "src_email": "Site officiel — nom + courriel publiés ensemble",
        "confidence": "Élevé",
        "why": "RH nommé + email publié. Plus accessible qu’un national.",
        "angle": "Contacter Lindsay pour chauffeurs / renforts ops.",
        "notes": "1 email direct publié (pas une déduction prenom.nom).",
    },
    {
        "name": "Transport Bourassa",
        "presence": "catalogue",
        "website": "https://bourassa.ca",
        "city": "Saint-Jean-sur-Richelieu",
        "sector": "Transport LTL / entrepôt",
        "employees": 600,
        "activity": "LTL Québec / Ontario / É.-U. — chauffeurs, manutention, mécaniciens",
        "hiring_signal": "Page carrières : recrutement@bourassa.ca — chauffeurs, manutention, mécaniciens",
        "offers": 2,
        "roles": "Chauffeurs ; manutention ; mécaniciens ; administration",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "recrutement@bourassa.ca",
                "kind": "recrutement",
                "who": "",
                "proof": "Page carrières officielle bourassa.ca/en/careers/ — déjà sur la fiche catalogue",
            },
        ],
        "phone": "450-346-5313",
        "address": "800, rue de Dijon, Saint-Jean-sur-Richelieu (QC) J3B 8G3",
        "src_co": "https://bourassa.ca",
        "src_job": "https://bourassa.ca/en/careers/",
        "src_person": "",
        "src_email": "Page carrières officielle",
        "confidence": "Élevé",
        "why": "LTL Rive-Sud avec inbox recrutement — déjà au catalogue, exclu à tort de la 1re passe.",
        "angle": "Manutentionnaires / chauffeurs à recrutement@bourassa.ca.",
        "notes": "1 email recrutement. Était déjà dans la base.",
    },
    {
        "name": "BOUTIN 3PL",
        "presence": "catalogue",
        "website": "https://www.boutin3pl.com",
        "city": "Boucherville",
        "sector": "3PL alimentaire",
        "employees": 80,
        "activity": "400 000 pi², 1800 conteneurs/an, SQF, 1400 Graham-Bell, Boucherville",
        "hiring_signal": "Ops alimentaire + cross-dock conteneurs — besoin structurel caristes/préparateurs",
        "offers": 0,
        "roles": "Préparation de commandes ; caristes ; débardeurs conteneurs",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": True,
        "repeat_roles": False,
        "hard_to_fill": True,
        "need_score": 3,
        "person1": "Jean-Philippe Boutin",
        "title1": "Direction / responsable des renseignements personnels",
        "li1": "",
        "emails": [
            {
                "addr": "info@boutin3pl.com",
                "kind": "general",
                "who": "",
                "proof": "Page Contact officielle boutin3pl.com/en/contact-us/ — « Send us an email info@boutin3pl.com »",
            },
            {
                "addr": "renseignements.personnels@boutin3pl.com",
                "kind": "other",
                "who": "Jean-Philippe Boutin — protection des RP",
                "proof": "Politique de confidentialité officielle boutin3pl.com/politique/",
            },
        ],
        "phone": "1-450-906-8900",
        "address": "1400, Graham-Bell, Boucherville (QC) J4B 6H5",
        "src_co": "https://www.boutin3pl.com/en/contact-us/",
        "src_job": "",
        "src_person": "Politique de confidentialité — Jean-Philippe Boutin",
        "src_email": "Site officiel EN contact (info@) + politique (renseignements.personnels@)",
        "confidence": "Élevé sur info@",
        "why": "3PL alimentaire Rive-Sud, décideur nommé, email officiel — manquait dans la 1re passe (preuve site EN).",
        "angle": "Préparateurs / caristes SQF à info@.",
        "notes": "2 emails. Doublon « Boutin 3PL » de la 1re passe fusionné ici.",
    },
    {
        "name": "Termont",
        "presence": "catalogue",
        "website": "https://termont.com",
        "city": "Montréal",
        "sector": "Terminal portuaire / quais",
        "employees": 400,
        "activity": "Terminal à conteneurs Port de Montréal",
        "hiring_signal": "Page carrières — Talent Acquisition, CV à carriere@",
        "offers": 1,
        "roles": "Ops terminal ; métiers de quai / maintenance",
        "shift": "Ops port 24/7",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "carriere@termont.com",
                "kind": "recrutement",
                "who": "Talent Acquisition",
                "proof": "Page carrières officielle termont.com/careers/",
            },
        ],
        "phone": "",
        "address": "Port de Montréal (QC)",
        "src_co": "https://termont.com/careers/",
        "src_job": "https://termont.com/careers/",
        "src_person": "",
        "src_email": "Site officiel carrières",
        "confidence": "Élevé",
        "why": "Quais portuaires — métiers physiques 24/7, inbox carrières.",
        "angle": "Métiers de quai / maintenance à carriere@.",
        "notes": "1 email recrutement.",
    },
    {
        "name": "Port de Montréal",
        "presence": "catalogue",
        "website": "https://www.port-montreal.com",
        "city": "Montréal",
        "sector": "Port / logistique",
        "employees": 1400,
        "activity": "Administration portuaire — ops maritimes/ferroviaires ; débardeurs via AEM",
        "hiring_signal": "Formulaire emplois + débardeurs via Association des employeurs maritimes",
        "offers": 1,
        "roles": "Ops maritimes / ferroviaires ; débardeurs (via AEM)",
        "shift": "Ops port",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "communications@port-montreal.com",
                "kind": "media",
                "who": "Siège — communications",
                "proof": "Page Contact us officielle port-montreal.com/en/contact-us",
            },
        ],
        "phone": "514-283-7011",
        "address": "2100, avenue Pierre-Dupuy, aile 1, Montréal (QC) H3C 3R5",
        "src_co": "https://www.port-montreal.com/en/contact-us",
        "src_job": "https://www.port-montreal.com/fr/emplois — formulaire ; débardeurs = mea.ca",
        "src_person": "",
        "src_email": "Page contact EN officielle. Les courriels du répertoire FR sont masqués (JS).",
        "confidence": "Élevé sur communications@",
        "why": "Écosystème portuaire. Débardeurs = AEM, pas l’APM.",
        "angle": "Ne pas envoyer des CV trieurs ici. communications@ = institutionnel.",
        "notes": "1 email communications. RH masqué sur le site FR.",
    },
    {
        "name": "QSL",
        "presence": "catalogue",
        "website": "https://qsl.com",
        "city": "Montréal",
        "sector": "Manutention portuaire",
        "employees": 1200,
        "activity": "Stevedoring / ops portuaires QC",
        "hiring_signal": "Ops portuaires — métiers de quai",
        "offers": 1,
        "roles": "Manutention portuaire ; ops",
        "shift": "Quais",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "info@qsl.com",
                "kind": "general",
                "who": "",
                "proof": "Site officiel qsl.com/fr/",
            },
        ],
        "phone": "",
        "address": "Ports QC",
        "src_co": "https://qsl.com/fr/",
        "src_job": "",
        "src_person": "",
        "src_email": "Accueil officiel",
        "confidence": "Élevé sur info@",
        "why": "Manutention portuaire — cousin des quais messagerie.",
        "angle": "info@ pour un premier contact ops/RH.",
        "notes": "1 email général.",
    },
    {
        "name": "Logistec",
        "presence": "catalogue",
        "website": "https://www.logistec.com",
        "city": "Montréal",
        "sector": "Manutention portuaire / environnement",
        "employees": 3000,
        "activity": "Stevedoring et services environnementaux, siège Montréal",
        "hiring_signal": "Portail carrières — ops portuaires",
        "offers": 1,
        "roles": "Ops portuaires ; environnementaux",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Montréal (QC)",
        "src_co": "https://www.logistec.com",
        "src_job": "Portail carrières Logistec",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu dans cette passe.",
        "confidence": "Faible sur le contact",
        "why": "Présent au catalogue, ops portuaires.",
        "angle": "Portail carrières.",
        "notes": "0 email.",
    },
    {
        "name": "Aéroports de Montréal",
        "presence": "catalogue",
        "website": "https://www.admtl.com",
        "city": "Dorval",
        "sector": "Aéroport / logistique",
        "employees": 1000,
        "activity": "YUL / YMX — ops 24/7, pas un 3PL mais écosystème cargo",
        "hiring_signal": "Portail carrières ADM — métiers techniques et opérations 24/7",
        "offers": 2,
        "roles": "Opérations aéroport ; maintenance ; électriciens ; sécurité",
        "shift": "24/7",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "YUL / YMX",
        "src_co": "https://www.admtl.com",
        "src_job": "Portail carrières ADM",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Moyen sur le volume 24/7 ; faible sur le contact",
        "why": "Écosystème cargo YUL (voisin FedEx/DHL/Frigologix).",
        "angle": "Portail ADM. Pas un client trieurs colis.",
        "notes": "0 email.",
    },
    {
        "name": "Ryder Canada",
        "presence": "indeed",
        "website": "https://www.ryder.com",
        "city": "Lachine",
        "sector": "3PL / entrepôt / transport",
        "employees": 2500,
        "activity": "Entrepôts et flotte QC (Lachine, Pointe-Claire) — caristes, commis, chauffeurs",
        "hiring_signal": "Veille Indeed : recruteur chauffeurs et entrepôt ; page contact Canada publie careers@",
        "offers": 3,
        "roles": "Warehouse associates ; forklift operators ; chauffeurs ; material handler",
        "shift": "Entrepôt multi-quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "careers@ryder.com",
                "kind": "recrutement",
                "who": "Travailler chez Ryder / questions processus",
                "proof": "Page Contact Canada officielle ryder.com/fr-ca/contact-us — « Travailler chez Ryder : careers@ryder.com » + portail iCIMS",
            },
        ],
        "phone": "1-905-826-8777",
        "address": "Lachine / Pointe-Claire (QC) — siège CA Concord (ON)",
        "src_co": "https://www.ryder.com/fr-ca/careers",
        "src_job": "https://jobs.ryder.com/ — warehousing",
        "src_person": "",
        "src_email": "Page contact officielle Canada",
        "confidence": "Élevé",
        "why": "3PL entrepôt GMA déjà vu dans la veille Indeed. Inbox careers@ publiée.",
        "angle": "Caristes / commis Lachine–Pointe-Claire à careers@ + portail.",
        "notes": "1 email recrutement. Un recruteur nommé sur une offre (salwa_…) n’est pas recopié ici (offre datée).",
    },
    {
        "name": "XPO Logistics",
        "presence": "indeed",
        "website": "https://www.xpo.com",
        "city": "Montréal",
        "sector": "LTL / quai",
        "employees": 2000,
        "activity": "LTL, quais Montréal",
        "hiring_signal": "Veille Indeed — Talent Acquisition ; quais LTL",
        "offers": 2,
        "roles": "Dock / LTL ; chauffeurs ; TA",
        "shift": "Quai",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Montréal (QC)",
        "src_co": "https://jobs.xpo.com/",
        "src_job": "https://jobs.xpo.com/",
        "src_person": "",
        "src_email": "earlycareer@xpo.com = campus US seulement, non retenu pour les quais Montréal.",
        "confidence": "Moyen sur le volume quais ; faible sur le contact QC",
        "why": "Quais LTL Montréal — cousin des messageries.",
        "angle": "Portail jobs.xpo.com. Pas d’inbox QC.",
        "notes": "0 email utile GMA.",
    },
    {
        "name": "Metro Supply Chain",
        "presence": "indeed",
        "website": "https://www.metroscg.com",
        "city": "Montréal",
        "sector": "3PL / entrepôt",
        "employees": 4000,
        "activity": "Siège 1002 Sherbrooke O. — conçoit et opère des entrepôts pour des marques",
        "hiring_signal": "Veille Indeed — Talent Acquisition Specialist ; warehouse & transportation",
        "offers": 2,
        "roles": "Warehouse & transportation operations ; TA",
        "shift": "Entrepôt",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "Mona Stefan",
        "title1": "Talent Acquisition Manager (LinkedIn public)",
        "li1": "https://www.linkedin.com/in/monastefan",
        "emails": [],
        "phone": "",
        "address": "1002, rue Sherbrooke Ouest, bureau 2000, Montréal (QC) H3A 3L6",
        "src_co": "https://www.metroscg.com/our-company/careers/",
        "src_job": "Portail carrières Metro SCG",
        "src_person": "LinkedIn public Mona Stefan — aucun email publié",
        "src_email": "Aucun courriel public. Formats prenom.nom@ interdits.",
        "confidence": "Élevé sur la personne TA ; nulle sur l’email",
        "why": "3PL montréalais de taille, TA interne. Pas d’inbox — contacter via portail / LinkedIn.",
        "angle": "Ne pas inventer mona.stefan@. Message LinkedIn + portail, bassin caristes.",
        "notes": "0 email. Personne TA identifiée sans courriel.",
    },
    {
        "name": "Schenker",
        "presence": "indeed",
        "website": "https://www.dbschenker.com/ca-fr",
        "city": "Dorval",
        "sector": "3PL / fret",
        "employees": 1500,
        "activity": "DB Schenker Canada, Dorval",
        "hiring_signal": "Veille Indeed — Recruiter",
        "offers": 1,
        "roles": "Entrepôt ; fret ; recruiter",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Dorval (QC)",
        "src_co": "https://www.dbschenker.com/ca-fr",
        "src_job": "https://www.dbschenker.com/ca-fr/carrieres",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible sur le contact",
        "why": "3PL aéroport Dorval.",
        "angle": "Portail Schenker.",
        "notes": "0 email.",
    },
    {
        "name": "Expeditors",
        "presence": "indeed",
        "website": "https://www.expeditors.com",
        "city": "Mirabel",
        "sector": "Transit / logistique",
        "employees": 800,
        "activity": "Expeditors Canada, Mirabel",
        "hiring_signal": "Veille Indeed — Talent Acquisition Partner",
        "offers": 1,
        "roles": "Transit ; TA",
        "shift": "",
        "ops_roles": False,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Mirabel (QC)",
        "src_co": "https://www.expeditors.com",
        "src_job": "https://www.expeditors.com/careers",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible",
        "why": "Présent dans la veille. Peu de trieurs/caristes visibles.",
        "angle": "Portail.",
        "notes": "0 email.",
    },
    {
        "name": "C.H. Robinson",
        "presence": "indeed",
        "website": "https://www.chrobinson.com",
        "city": "Laval",
        "sector": "Courtage transport",
        "employees": 1000,
        "activity": "Courtage, bureau Laval — peu d’entrepôt propre",
        "hiring_signal": "Veille Indeed — Recruiter",
        "offers": 1,
        "roles": "Courtage ; recruiter",
        "shift": "",
        "ops_roles": False,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 1,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Laval (QC)",
        "src_co": "https://www.chrobinson.com",
        "src_job": "https://www.chrobinson.com/careers",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible — pas un employeur trieurs",
        "why": "Dans la veille, mais courtier : pas le bon persona trieurs/caristes.",
        "angle": "Ne pas prioriser pour les trieurs.",
        "notes": "0 email. Score besoin 1/5.",
    },
    {
        "name": "Penske",
        "presence": "indeed",
        "website": "https://www.penske.com",
        "city": "Boucherville",
        "sector": "Logistique / location flotte",
        "employees": 800,
        "activity": "Penske Logistics Canada, Boucherville",
        "hiring_signal": "Veille Indeed — Recruiter",
        "offers": 1,
        "roles": "Logistique ; flotte",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Boucherville (QC)",
        "src_co": "https://www.penske.com/careers",
        "src_job": "https://www.penske.com/careers",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible",
        "why": "Présent veille Indeed, Rive-Sud.",
        "angle": "Portail Penske.",
        "notes": "0 email.",
    },
    {
        "name": "Transport Besner",
        "presence": "indeed",
        "website": "https://www.transport-besner.com",
        "city": "Boucherville",
        "sector": "Transport / logistique",
        "employees": 600,
        "activity": "Transport QC, RH à Lévis, possibilité Montréal ; page emplois publie recrutement@",
        "hiring_signal": "Page Carrières : « communiquez avec RH — recrutement@besner.com » + brokers/chauffeurs",
        "offers": 2,
        "roles": "Chauffeurs / brokers ; mécanicien ; logistique ; répartition",
        "shift": "",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "recrutement@besner.com",
                "kind": "recrutement",
                "who": "Ressources humaines",
                "proof": "Page Carrières officielle transport-besner.com/jobs — « Par courriel : recrutement@besner.com »",
            },
        ],
        "phone": "418-834-0463 poste 2323",
        "address": "1950, 3e Rue, Lévis (QC) — ops aussi Boucherville / Montréal",
        "src_co": "https://www.transport-besner.com/jobs",
        "src_job": "Même page + offres brokers (possibilité Montréal)",
        "src_person": "",
        "src_email": "Page carrières officielle",
        "confidence": "Élevé",
        "why": "Inbox recrutement publiée, déjà dans la veille Indeed.",
        "angle": "Chauffeurs / logistique à recrutement@besner.com.",
        "notes": "1 email RH. vmarceau@ vu sur un agrégateur — non retenu (pas le site).",
    },
    {
        "name": "Logistik Unicorp",
        "presence": "indeed",
        "website": "https://www.logistikunicorp.com",
        "city": "Saint-Jean-sur-Richelieu",
        "sector": "Logistique textile / entrepôt",
        "employees": 1200,
        "activity": "CD uniforme / textile, 820 ch. du Grand Bernier Nord",
        "hiring_signal": "Veille Indeed — conseiller acquisition de talents ; page carrières « contactez RH »",
        "offers": 2,
        "roles": "Entrepôt textile ; TA ; commis",
        "shift": "Entrepôt",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "info@logistikunicorp.com",
                "kind": "general",
                "who": "",
                "proof": "Page LinkedIn officielle de l’entreprise — email publié",
            },
        ],
        "phone": "1-888-326-8688",
        "address": "820, chemin du Grand Bernier Nord, Saint-Jean-sur-Richelieu (QC) J2W 0A6",
        "src_co": "https://www.logistikunicorp.com/carrieres/post.asp",
        "src_job": "Portail carrières Logistik Unicorp",
        "src_person": "",
        "src_email": "LinkedIn entreprise (info@). rh@logistikunicorp.com non vu — non inventé.",
        "confidence": "Moyen sur info@ (LinkedIn entreprise, pas le HTML carrières)",
        "why": "Gros CD Rive-Sud, TA interne.",
        "angle": "Portail + info@ si besoin. Ne pas inventer rh@.",
        "notes": "1 email général. Page carrières dit « contactez RH » sans publier l’adresse.",
    },
    {
        "name": "Sysco Québec",
        "presence": "catalogue",
        "website": "https://www.sysco.ca",
        "city": "Montréal",
        "sector": "Distribution alimentaire / CD",
        "employees": 3000,
        "activity": "CD foodservice — préparateurs, caristes, chauffeurs, chambre froide",
        "hiring_signal": "Page Sysco Recrute Grand Montréal — rh@ publié",
        "offers": 3,
        "roles": "Caristes ; préparateurs ; chauffeurs-livreurs ; chambre froide",
        "shift": "Entrepôt alimentaire multi-quarts",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "rh@mtl.sysco.ca",
                "kind": "rh",
                "who": "Sysco Recrute Grand Montréal",
                "proof": "Page officielle sysco.ca/grandmontreal/Recrute",
            },
        ],
        "phone": "",
        "address": "Grand Montréal (QC)",
        "src_co": "https://www.sysco.ca/grandmontreal/Recrute",
        "src_job": "https://careers.sysco.com/",
        "src_person": "",
        "src_email": "Page recrutement officielle Grand Montréal",
        "confidence": "Élevé",
        "why": "CD alimentaire GMA — caristes/nuit, inbox RH locale.",
        "angle": "Caristes / préparateurs chambre froide à rh@mtl.sysco.ca.",
        "notes": "1 email RH local. Excellent contact.",
    },
    {
        "name": "McKesson Canada",
        "presence": "catalogue",
        "website": "https://www.mckesson.ca",
        "city": "Montréal",
        "sector": "Distribution pharma / CD",
        "employees": 4000,
        "activity": "CD pharmaceutiques QC — caristes, préparateurs, environnement réglementé",
        "hiring_signal": "Portail carrières — caristes et préparation de commandes",
        "offers": 2,
        "roles": "Caristes ; préparateurs ; pharmaciens d’entrepôt ; chauffeurs",
        "shift": "CD multi-quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Entrepôts QC",
        "src_co": "https://www.mckesson.ca",
        "src_job": "Portail carrières McKesson",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Moyen sur le volume CD ; faible sur le contact",
        "why": "CD pharma — caristes réglementés, déjà au catalogue.",
        "angle": "Portail McKesson. Ne pas inventer rh@.",
        "notes": "0 email.",
    },
    {
        "name": "Sobeys Québec",
        "presence": "catalogue",
        "website": "https://www.sobeyscareers.com",
        "city": "Montréal",
        "sector": "CD alimentaire",
        "employees": 20000,
        "activity": "Entrepôts IGA / Sobeys QC — caristes, préparateurs",
        "hiring_signal": "Portail sobeyscareers.com — recrutement massif caristes",
        "offers": 3,
        "roles": "Caristes ; préparateurs ; maintenance d’entrepôt",
        "shift": "CD alimentaire multi-quarts",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "CD IGA / Sobeys QC",
        "src_co": "https://www.sobeyscareers.com/",
        "src_job": "https://www.sobeyscareers.com/",
        "src_person": "",
        "src_email": "Aucun courriel RH public — portail only.",
        "confidence": "Élevé sur le volume ; nulle sur l’email",
        "why": "Gros employeur caristes QC.",
        "angle": "Portail Sobeys. Pas d’inbox.",
        "notes": "0 email.",
    },
    {
        "name": "Amazon Canada",
        "presence": "catalogue",
        "website": "https://www.amazon.jobs",
        "city": "Montréal",
        "sector": "Fulfillment / entrepôt",
        "employees": 8000,
        "activity": "Centres de fulfillment QC — associés, caristes, quarts rotatifs",
        "hiring_signal": "Portail amazon.jobs — volume élevé",
        "offers": 5,
        "roles": "Associés ; caristes ; supervision",
        "shift": "Quarts rotatifs",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 5,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Fulfillment QC",
        "src_co": "https://www.amazon.jobs",
        "src_job": "https://www.amazon.jobs",
        "src_person": "",
        "src_email": "Aucun courriel RH public — 100 % portail.",
        "confidence": "Élevé sur le volume ; nulle sur l’email",
        "why": "Volume caristes maximal. Recrutement injoignable par courriel.",
        "angle": "Ne pas prioriser un cold email. Portail seulement.",
        "notes": "0 email. Pénalité centralisation.",
    },
    {
        "name": "Costco Wholesale",
        "presence": "catalogue",
        "website": "https://www.costco.ca",
        "city": "Montréal",
        "sector": "Entrepôt-club / CD",
        "employees": 5000,
        "activity": "Entrepôts-clubs QC — métiers d’entrepôt, quarts",
        "hiring_signal": "Recrutement volume entrepôt",
        "offers": 2,
        "roles": "Entrepôt ; réception ; magasin",
        "shift": "Quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Clubs QC",
        "src_co": "https://www.costco.ca",
        "src_job": "Portail carrières Costco",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible sur le contact",
        "why": "Volume entrepôt, déjà au catalogue.",
        "angle": "Portail Costco.",
        "notes": "0 email.",
    },
    {
        "name": "Home Depot Canada",
        "presence": "catalogue",
        "website": "https://www.homedepot.ca",
        "city": "Montréal",
        "sector": "CD quincaillerie",
        "employees": 4000,
        "activity": "Centres de distribution QC — caristes, réception",
        "hiring_signal": "Recrutement CD / entrepôt",
        "offers": 1,
        "roles": "Caristes ; réception ; entrepôt",
        "shift": "CD",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "CD QC",
        "src_co": "https://www.homedepot.ca",
        "src_job": "Portail carrières Home Depot",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible sur le contact",
        "why": "CD déjà au catalogue — caristes.",
        "angle": "Portail Home Depot.",
        "notes": "0 email.",
    },
    {
        "name": "Canadian Tire",
        "presence": "catalogue",
        "website": "https://corp.canadiantire.ca",
        "city": "Montréal",
        "sector": "CD commerce",
        "employees": 8000,
        "activity": "CD et réseau magasin — caristes / entrepôt",
        "hiring_signal": "FAQ carrières publie careers@",
        "offers": 2,
        "roles": "Caristes ; entrepôt ; magasin",
        "shift": "CD",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "careers@cantire.com",
                "kind": "recrutement",
                "who": "",
                "proof": "FAQ carrières officielle corp.canadiantire.ca/English/careers/default.aspx",
            },
        ],
        "phone": "",
        "address": "CD / magasins QC",
        "src_co": "https://corp.canadiantire.ca/English/careers/default.aspx",
        "src_job": "Portail carrières Canadian Tire",
        "src_person": "",
        "src_email": "FAQ carrières officielle",
        "confidence": "Élevé sur careers@",
        "why": "Inbox carrières publiée + volume CD.",
        "angle": "Caristes CD à careers@cantire.com.",
        "notes": "1 email recrutement (corporate, pas un TA local).",
    },
    {
        "name": "Walmart Canada",
        "presence": "catalogue",
        "website": "https://www.walmartcanada.ca",
        "city": "Montréal",
        "sector": "CD commerce",
        "employees": 10000,
        "activity": "CD et magasins QC",
        "hiring_signal": "Recrutement volume entrepôt / magasin",
        "offers": 2,
        "roles": "Entrepôt ; magasin",
        "shift": "CD",
        "ops_roles": True,
        "night_shift": True,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 3,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "cacustrel@wal-mart.com",
                "kind": "general",
                "who": "Relations clients Canada (pas RH)",
                "proof": "Politiques officielles walmartcanada.ca/policies",
            },
        ],
        "phone": "",
        "address": "CD / magasins QC",
        "src_co": "https://www.walmartcanada.ca/policies",
        "src_job": "Portail carrières Walmart",
        "src_person": "",
        "src_email": "Politiques Canada. Pas une inbox recrutement.",
        "confidence": "Élevé sur cacustrel@ ; nulle sur RH",
        "why": "Volume CD, déjà au catalogue. Contact RH = portail.",
        "angle": "Ne pas pitcher cacustrel@. Portail Walmart.",
        "notes": "1 email service client.",
    },
    {
        "name": "SAQ",
        "presence": "catalogue",
        "website": "https://www.saq.com",
        "city": "Montréal",
        "sector": "CD / distribution",
        "employees": 7000,
        "activity": "CD et magasin — caristes, préparateurs, conseillers",
        "hiring_signal": "Portail carrières SAQ très actif (entrepôt, caristes)",
        "offers": 3,
        "roles": "Caristes ; préparateurs de commandes ; conseillers",
        "shift": "CD multi-quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "demandes@saq.com",
                "kind": "general",
                "who": "Demandes générales (aspects légaux)",
                "proof": "Page aspects légaux officielle saq.com/en/legal-aspects",
            },
        ],
        "phone": "",
        "address": "CD SAQ QC",
        "src_co": "https://www.saq.com/fr/carrieres",
        "src_job": "https://www.saq.com/fr/carrieres",
        "src_person": "",
        "src_email": "Page légale. Recrutement = portail.",
        "confidence": "Élevé sur demandes@ ; nulle sur RH",
        "why": "Gros employeur caristes QC.",
        "angle": "Portail SAQ. demandes@ n’est pas RH.",
        "notes": "1 email général.",
    },
    {
        "name": "Colabor",
        "presence": "catalogue",
        "website": "https://www.colabor.com",
        "city": "Saint-Bruno-de-Montarville",
        "sector": "Distribution alimentaire / CD",
        "employees": 700,
        "activity": "Entrepôt Saint-Bruno + Lévis, Rimouski, Chicoutimi — caristes, préparateurs, chauffeurs",
        "hiring_signal": "info@ publié ; caristes / préparateurs / chauffeurs",
        "offers": 2,
        "roles": "Caristes ; préparateurs ; chauffeurs",
        "shift": "CD alimentaire",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": True,
        "hard_to_fill": True,
        "need_score": 4,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [
            {
                "addr": "info@colabor.com",
                "kind": "general",
                "who": "",
                "proof": "Site officiel — courriel publié (fiche catalogue)",
            },
        ],
        "phone": "",
        "address": "1601, René-Descartes, Saint-Bruno-de-Montarville (QC)",
        "src_co": "https://www.colabor.com",
        "src_job": "Portail / page carrières Colabor",
        "src_person": "",
        "src_email": "Site officiel",
        "confidence": "Élevé sur info@",
        "why": "CD alimentaire Rive-Sud, plus accessible qu’un géant.",
        "angle": "Caristes / préparateurs Saint-Bruno à info@.",
        "notes": "1 email général.",
    },
    {
        "name": "Livingston International",
        "presence": "catalogue",
        "website": "https://www.livingstonintl.com",
        "city": "Montréal",
        "sector": "Douane / courtage",
        "employees": 2000,
        "activity": "Courtage douanier — peu de trieurs/caristes",
        "hiring_signal": "Portail carrières",
        "offers": 0,
        "roles": "Courtage ; conformité",
        "shift": "",
        "ops_roles": False,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": False,
        "centralized": True,
        "need_score": 1,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Bureaux QC",
        "src_co": "https://www.livingstonintl.com",
        "src_job": "Portail carrières Livingston",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible — hors persona trieurs",
        "why": "Au catalogue logistique, mais ce n’est pas un hub de tri.",
        "angle": "Ne pas prioriser pour trieurs/caristes.",
        "notes": "0 email. Score besoin 1/5.",
    },
    {
        "name": "CPKC",
        "presence": "catalogue",
        "website": "https://www.cpkcr.com",
        "city": "Montréal",
        "sector": "Ferroviaire",
        "employees": 20000,
        "activity": "Réseau ferroviaire QC — pas un hub colis",
        "hiring_signal": "Portail carrières CPKC — métiers techniques",
        "offers": 1,
        "roles": "Mécaniciens de locomotive ; métiers de voie ; ateliers",
        "shift": "Quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Réseau QC",
        "src_co": "https://www.cpkcr.com",
        "src_job": "Portail carrières CPKC",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible sur le contact",
        "why": "Au catalogue. Pas le persona trieurs colis.",
        "angle": "Portail CPKC.",
        "notes": "0 email.",
    },
    {
        "name": "Canadien National",
        "presence": "catalogue",
        "website": "https://www.cn.ca",
        "city": "Montréal",
        "sector": "Ferroviaire",
        "employees": 24000,
        "activity": "Siège Montréal — métiers ferroviaires",
        "hiring_signal": "Portail carrières CN",
        "offers": 1,
        "roles": "Métiers ferroviaires ; ateliers",
        "shift": "Quarts",
        "ops_roles": True,
        "night_shift": False,
        "growth": False,
        "repeat_roles": False,
        "hard_to_fill": True,
        "centralized": True,
        "need_score": 2,
        "person1": "",
        "title1": "",
        "li1": "",
        "emails": [],
        "phone": "",
        "address": "Montréal (QC)",
        "src_co": "https://www.cn.ca",
        "src_job": "Portail carrières CN",
        "src_person": "",
        "src_email": "Aucun courriel RH public retenu.",
        "confidence": "Faible sur le contact",
        "why": "Au catalogue. Pas un hub colis.",
        "angle": "Portail CN.",
        "notes": "0 email.",
    },
]